# angle_finder
realsense_fov: 1.204277184 # radians
realsense_res_x: 1920 #pixel width of image frames

# coord_finder
angle_error_adjustment: 0.0 #radians TUNING

# fake_angle_finder
theta_1: 1 #radians
theta_2: 3 #radians

